@base = http://localhost:8082
DELETE {{base}}/delete/1
###
GET {{base}}/1
###
GET {{base}}/
###
POST {{base}}/
Content-Type: application/json

{
    "technicianName":"Manikandan",
    "username":"mani",
    "password":"salem",
    "contact":965676455
}